version: '3.8'

services:
  postgress:
    image: postgres:13
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  camunda:
    image: camunda/camunda-bpm-platform:latest
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgress:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
    ports:
      - "8080:8080"
    depends_on:
      - postgress

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9090:9090"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9090
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  camunda_service:
    build:
      context: ./camunda_service
      dockerfile: Dockerfile
    container_name: camunda_service
    depends_on:
      - broker
      - camunda
      - postgress
    ports:
      - "8081:8081"
    environment:
      - CAMUNDA_BPM_CLIENT_BASE_URL=http://camunda:8080/engine-rest
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgress:5432/camunda
      - SPRING_DATASOURCE_USERNAME=camunda
      - SPRING_DATASOURCE_PASSWORD=camunda
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop


  task_service:
    build:
      context: ./task_service
      dockerfile: Dockerfile
    container_name: task_service
    depends_on:
      - broker
      - postgress
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgress:5432/camunda
      - SPRING_DATASOURCE_USERNAME=camunda
      - SPRING_DATASOURCE_PASSWORD=camunda
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  postgres-data: